# III. Cuspidality analysis: the non cuspidal case

In this session, we will analyse the cuspidality of elementary robots using `AlgebraicSolving.jl`.

In [1]:
using Pkg, Plots, AlgebraicSolving
import AlgebraicSolving.change_ringvar, AlgebraicSolving.gens, AlgebraicSolving.factor

In [2]:
function log(msg)
    println(msg)
    flush(stdout)
end

log (generic function with 1 method)

### A 3 revolute joint orthogonal robot:
![A 3R robot](slides/images/robot/3rrobot-shrink.png)

We now consider a robot whose algebraic kinematic map is:
$$
\begin{array}{cccc}
     \mathcal{K} \colon& V &\longrightarrow & \mathbb{R}^3 \\
     &(c_1,c_2, c_3, s_1, s_2, s_3) &\longmapsto
    &\big(z_1(\bm{c},\bm{s}), z_2(\bm{c},\bm{s}),z_3(\bm{c},\bm{s})\big)
 \end{array}
 $$

where
$$\left\{\begin{array}{l}
 z_1 = \frac{1}{10}c_1c_2(15c_3 + 11) - \frac{1}{10}s_1(15s_3 + 13) + 3c_1\\[.5em]
 z_2 = \frac{1}{10}c_1c_2(15c_3 + 11) + \frac{1}{10}c_1(15s_3 + 13) + 3s_1\\[[.5em]
z_3 = -\frac{1}{10}s_2(15c_3 + 11)
 \end{array}\right.$$

In [3]:
# Polar variety
R,(c1,c2,c3,s1,s2,s3) = polynomial_ring(QQ, [:c1,:c2,:c3,:s1,:s2,:s3])
V = Ideal([ c1^2 + s1^2 - 1, c2^2 + s2^2 - 1, c3^2 + s3^2 - 1 ])
K = 1//10 * [ c1*c2*(15*c3+11) - s1*(15*s3+13) + 3c1, c1*c2*(15*c3+11) - c1*(15*s3+13) + 3s1, -s2*(15*c3+11) ]
critK = computepolar(1:3, V, phi=K)

4-element Vector{QQMPolyRingElem}:
 c1^2 + s1^2 - 1
 c2^2 + s2^2 - 1
 c3^2 + s3^2 - 1
 27*c1^2*c2^2*c3*s3^2 + 144//5*c1^2*c2^2*c3*s3 + 99//5*c1^2*c2^2*s3^2 + 528//25*c1^2*c2^2*s3 + 27*c1^2*c2*c3^2*s3 + 117//5*c1^2*c2*c3^2 + 99//5*c1^2*c2*c3*s3 + 429//25*c1^2*c2*c3 + 27*c1^2*c3*s2^2*s3^2 + 144//5*c1^2*c3*s2^2*s3 + 99//5*c1^2*s2^2*s3^2 + 528//25*c1^2*s2^2*s3 + 27*c1*c2^2*c3^3*s1 + 198//5*c1*c2^2*c3^2*s1 + 27*c1*c2^2*c3*s1*s3^2 + 144//5*c1*c2^2*c3*s1*s3 + 363//25*c1*c2^2*c3*s1 + 99//5*c1*c2^2*s1*s3^2 + 528//25*c1*c2^2*s1*s3 + 54//5*c1*c2*c3^2*s1 + 198//25*c1*c2*c3*s1 + 27*c1*c3*s1*s2^2*s3^2 + 144//5*c1*c3*s1*s2^2*s3 + 99//5*c1*s1*s2^2*s3^2 + 528//25*c1*s1*s2^2*s3 - 27*c2^2*c3^3*s1^2 - 198//5*c2^2*c3^2*s1^2 - 363//25*c2^2*c3*s1^2 + 27*c2*c3^2*s1^2*s3 + 117//5*c2*c3^2*s1^2 + 99//5*c2*c3*s1^2*s3 + 429//25*c2*c3*s1^2

Cuspidal candidates

In [4]:
R_polar, (c2,c3,s2,s3,rho,z) = polynomial_ring(QQ, [:c2,:c3,:s2,:s3,:rho,:z])
K_polar, critK_polar = [ [ f(1,c2,c3,0,s2,s3) for f in E if !iszero(f(1,c2,c3,0,s2,s3))] for E in [K, critK] ]
KcritK_polar = Ideal(vcat([z - K_polar[end], rho^2 - K_polar[1]^2 - K_polar[2]^2], critK_polar))

G = eliminate(KcritK_polar, 4)

R1_polar, (rho,z) = polynomial_ring(QQ, [:rho,:z])
svalK_polar = [ g(1,1,1,1,rho,z) for g in G ]

Wsval_polar = points_per_components(QQMPolyRingElem[], [rho], svalK_polar, info_level=2)

Bivariate sample points        36 / 36 (2.465 s) (done)


60-element Vector{Vector{Vector{QQFieldElem}}}:
 [[58956388620730403428603//302231454903657293676544, 58956388620730403428603//302231454903657293676544], [0, 0]]
 [[483957286616351615804397//1208925819614629174706176, 483957286616351615804397//1208925819614629174706176], [0, 0]]
 [[18207989059025487805//36893488147419103232, 18207989059025487805//36893488147419103232], [0, 0]]
 [[102743936261030507893282704355//158456325028528675187087900672, 102743936261030507893282704355//158456325028528675187087900672], [-2, -2]]
 [[102743936261030507893282704355//158456325028528675187087900672, 102743936261030507893282704355//158456325028528675187087900672], [0, 0]]
 [[102743936261030507893282704355//158456325028528675187087900672, 102743936261030507893282704355//158456325028528675187087900672], [2, 2]]
 [[540557635780024039308488355725//633825300114114700748351602688, 540557635780024039308488355725//633825300114114700748351602688], [-2, -2]]
 [[540557635780024039308488355725//633825300114114700748

Roadmap

In [5]:
R_rab,(u,c2,c3,s2,s3) = polynomial_ring(QQ, [:u,:c2,:c3,:s2,:s3])
critK_rab = [ f(c2,c3,s2,s3,0,0) for f in critK_polar ]
K1_rab = [ f(c2,c3,s2,s3,0,0) for f in K_polar ]

Vmcrit_rab = vcat(critK_rab[1:end-1], 1 - u*critK_rab[end])

Wcusp_rab = [ vcat(Vmcrit_rab, sum(rfib)//2 - K1_rab[1]^2 - K1_rab[2]^2, sum(zfib)//2 - K1_rab[end]) for (rfib, zfib) in Wsval_polar ]


60-element Vector{Vector{QQMPolyRingElem}}:
 [c2^2 + s2^2 - 1, c3^2 + s3^2 - 1, -27*u*c2^2*c3*s3^2 - 144//5*u*c2^2*c3*s3 - 99//5*u*c2^2*s3^2 - 528//25*u*c2^2*s3 - 27*u*c2*c3^2*s3 - 117//5*u*c2*c3^2 - 99//5*u*c2*c3*s3 - 429//25*u*c2*c3 - 27*u*c3*s2^2*s3^2 - 144//5*u*c3*s2^2*s3 - 99//5*u*s2^2*s3^2 - 528//25*u*s2^2*s3 + 1, -9//2*c2^2*c3^2 - 33//5*c2^2*c3 - 121//50*c2^2 + 9//2*c2*c3*s3 + 3*c2*c3 + 33//10*c2*s3 + 11//5*c2 - 9//4*s3^2 - 39//10*s3 - 11975390027694489482891133//7555786372591432341913600, 3//2*c3*s2 + 11//10*s2]
 [c2^2 + s2^2 - 1, c3^2 + s3^2 - 1, -27*u*c2^2*c3*s3^2 - 144//5*u*c2^2*c3*s3 - 99//5*u*c2^2*s3^2 - 528//25*u*c2^2*s3 - 27*u*c2*c3^2*s3 - 117//5*u*c2*c3^2 - 99//5*u*c2*c3*s3 - 429//25*u*c2*c3 - 27*u*c3*s2^2*s3^2 - 144//5*u*c3*s2^2*s3 - 99//5*u*s2^2*s3^2 - 528//25*u*s2^2*s3 + 1, -9//2*c2^2*c3^2 - 33//5*c2^2*c3 - 121//50*c2^2 + 9//2*c2*c3*s3 + 3*c2*c3 + 33//10*c2*s3 + 11//5*c2 - 9//4*s3^2 - 39//10*s3 - 41698266807442207879314907//30223145490365729367654400, 3//2*c3*s2 + 11

In [6]:
# Real root isolation
Wcusp_isolated_rab = vcat(filter(!isempty, [ real_solutions(Ideal(w), interval=true)  for w in Wcusp_rab ])...)

116-element Vector{Vector{Vector{QQFieldElem}}}:
 [[-6757261285222217775//9223372036854775808, -3378630642611108875//4611686018427387904], [-9223372036854775815//9223372036854775808, -9223372036854775801//9223372036854775808], [-7761503354693765149//18446744073709551616, -3880751677346882563//9223372036854775808], [0, 0], [-1071004065311276537371//1180591620717411303424, -2142008130622553074741//2361183241434822606848]]
 [[-1554003994251877869//1152921504606846976, -6216015977007510585//4611686018427387904], [9223372036854775411//9223372036854775808, 9223372036854776205//9223372036854775808], [-2946419992500606581//4611686018427387904, -5892839985001212421//9223372036854775808], [0, 0], [-113526769231753502101//147573952589676412928, -28381692307938375525//36893488147419103232]]
 [[8674438455636780895//2305843009213693952, 69395507645094247383//18446744073709551616], [576460752303423487//576460752303423488, 576460752303423489//576460752303423488], [-13949597339396182693//18446744073709

In [10]:
RM_rab = roadmap(Ideal(Vmcrit_rab), Wcusp_isolated_rab, 1)

Try linear forms QQMPolyRingElem[u, c2]
Compute L1-critical points: K1
Compute L_e2-polar variety: W
Compute W-critical points with <<vertical>> tangent: K1W


Vector{Tuple{QQMPolyRingElem, QQFieldElem}}[[], [(u, -292625329//67438776)], [(u, -1278765037//886838838)], [(u, -52200719//38727913)], [(u, -1106339565//996606466)], [(u, -1401709927//1271024930)], [(u, -486635075//442121903)], [(u, -890605749//809426401)], [(u, -1181850321//1074722314)], [(u, -1353044230//1281765263)]  …  [(u, 1172272145//5862494799)], [(u, 500614139//2452010483)], [(u, 169759868//625731105)], [(u, 642112474//2012159591)], [(u, 350614567//900046983)], [(u, 412587440//1007246351)], [(u, 209976926//386963197)], [(u, 366179055//526751278)], [(u, 425332077//113061958)], [(u, 808538660//58853493)]]

In [11]:
hilbert_degree.(all_eqs(RM_rab))

95-element Vector{Int64}:
 52
 16
 16
 16
 16
 16
 16
 16
 16
 16
  ⋮
 16
 16
 16
 16
 16
 16
 16
 16
 16

In [9]:
# Takes ~1h20 (1h06 for the first curve)
#GRM_rab = curve_arrangement_graph(all_eqs(RM_rab), Ideal.(Wcusp_rab), generic=10, v=2)